### ISSUE TITLE
Does it actually use the cache it builds?

### ISSUE THREAD

**Issue by tolnem** [jdevalk/pdf-xml-sitemap#1]
I'm not actually using this plugin, I was only reading it for inspiration since I needed to build a custom sitemap myself and figured a new plugin from you would be the best source for how to do it. :) 

It struck me as I was reading the code that it doesn't look like it ever uses the list of pdfs from the transient.

Am I missing something, or wouldn't `$this->pdfs` always be empty when `retrieve_from_cache_or_build` runs?

It gets the transient and adds a comment to the output, but it doesn't set `$this->pdfs`?

**Comment by jdevalk** [comment]
You're 100% right. 🤦
