### ISSUE TITLE
Missing Image Dimensions...

### ISSUE THREAD

**Issue by JohnHFly** [jdevalk/pdf-xml-sitemap#2]
Hi Joost

I'm John, we have a website using your pdf-xml sitemap plugin and having recently upgraded to WP 6.1.1 we noticed an issue whereby images uploaded to the WP media library are not having their dimensions detected. After much trial and error, the issue was isolated to your plugin. I set up a staging site with twenty nineteen theme and only your plugin activated - the image dimension issue occured. Deactivate your plugin and the image dimension issue was resolved. Example gif of the image dimensions I am referring to here: https://talk2fly.d.pr/i/jOIotV

Unfortunately I have not identified the actual issue in the code, just isolated it to your plugin as described.

Would appreciate your thoughts - eg. if you're able to replicate the issue / release an update accordingly that would be great
Cheers
John

**Comment by jhoell** [comment]
I have encountered the exact same issue and determined this plugin to be the cause as well. The image also does not show its preview in the admin when clicking on it. This only seems to apply to images uploaded while this plugin is active. Deactivating the plugin, everything works as normal again.

**Comment by skollasch** [comment]
I have also encountered the exact same issue.

**Comment by jdevalk** [comment]
I've just found and fixed it, release incoming.
